### 服务端口号
server:
  port: 8300

### eureka 基本信息配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka

### Spring 配置
spring:
  application:
    name:  group-service-test

####swagger相关配置
swagger:
  base-package: com.huweilong.group.service.test.impl
  title: 分布式服务 - 分布式测试服务
  description: 分布式服务 - 分布式测试服务
  version: 1.0.0
  terms-of-service-url: http://www.huweilong.com/
  contact:
    name: Alex
    email: Alex_2713@126.com
