### 服务端口号
server:
  port: 8300

### eureka 基本信息配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka.huweilong.com/eureka

### Spring 配置
spring:
  application:
    name:  group-service-test
  datasource:
    ### 数据库连接驱动
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    ### 数据库连接地址
    url: jdbc:p6spy:mysql://10.123.199.21:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    ### 数据库连接用户名
    username: root
    ### 数据库连接密码
    password: Hu371329
    druid:
      ### 初始化连接数
      initial-size: 10
      ### 最大活跃连接数
      max-active: 100
      ### 最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
      min-idle: 10
      ### 最大等待值
      max-wait: 60000
      ### 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      ### 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      ### 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      ### 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      web-stat-filter:
        ### 是否启用StatFilter默认值true
        enabled: true
        url-pattern: /*
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.png"
          - "*.css"
          - "*.ico"
          - "/druid/*"
      stat-view-servlet:
        ### 展示Druid的统计信息
        enabled: true
        reset-enable: false
        url-pattern: /druid/*
        login-username: HuWeilong
        login-password: Hu371329
        allow: ""
      filter:
        stat:
          ### slowSqlMillis用来配置SQL慢的标准，执行时间超过slowSqlMillis的就是慢。
          log-slow-sql: true
          ### slowSqlMillis的缺省值为3000，也就是3秒
          slow-sql-millis: 2000
          ### SQL合并配置
          merge-sql: true
          db-type: mysql
          enabled: true
        wall:
          config:
            ### 允许执行多条SQL
            multi-statement-allow: true
  redis:
    ### Redis服务器数据库
    database: 0
    ### Redis服务器地址
    host: 10.123.199.21
    ### Redis服务器连接端口
    port: 6379
    ### Redis服务器连接密码（默认为空）
    password: Hu371329
    ### 连接超时时间（毫秒）
    timeout: 10000
    ### 连接池设置
    lettuce:
      pool:
        ### 连接池中的最大空闲连接
        max-idle: 8
        ### 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ### 连接池中的最小空闲连接
        min-idle: 1
        ### 连接池最大连接数（使用负值表示没有限制）
        max-active: 8

security:
  auth:
    server: http://auth.huweilong.com/
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: Hu371329
      user-authorization-uri: ${security.auth.server}/oauth/authorize
      access-token-uri: ${security.auth.server}/oauth/token
      scope: all
      pre-established-redirect-uri: http://test.huweilong.com/login
      use-current-uri: false
    resource:
      jwt:
        key-uri: ${security.auth.server}/oauth/token_key
      user-info-uri: ${security.auth.server}/user

mybatis-plus:
  global-config:
    db-config:
      ### 全局逻辑删除的实体字段名(配置后可以忽略字段的配置)
      logic-delete-field: activeFlag
      ### 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      ### 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  ### 枚举配置
  type-enums-package: com.huweilong.group.service.test.entity.em

####swagger相关配置
swagger:
  base-package: com.huweilong.group.service.test.impl
  title: 分布式服务 - 分布式测试服务
  description: 分布式服务 - 分布式测试服务
  version: 1.0.0
  terms-of-service-url: http://www.huweilong.com/
  contact:
    name: Alex
    email: Alex_2713@126.com
    url: http://www.huweilong.com/
