### 服务端口号
server:
  port: 8102

### eureka 基本信息配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/eureka

### Spring 配置
spring:
  application:
    name:  group-service-system
  ### resources
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  ### freemarker
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: utf-8
    request-context-attribute: request
    settings:
      number_format: 0.##########

### xxl-sso
xxl:
  sso:
    redis:
      address: redis://:Hu371329@10.123.199.21:6379/0
      expire:
        minute: 1440
