### 服务端口号
server:
  port: 8102
  servlet:
    context-path: /sso

### eureka 基本信息配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka.huweilong.com/eureka

### Spring 配置
spring:
  application:
    name:  group-service-system
